# Catppuccin v2

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 1

[window.padding]
x = 15
y = 15

[colors.normal]
black = "#24273a"
red = "#ed8796"
green = "#8aadf4"
yellow = "#c6a0f6"
blue = "#8aadf4"
magenta = "#c6a0f6"
cyan = "#8aadf4"
white = "#8aadf4"

[colors.primary]
background = "#1e2030"
foreground = "#8aadf4"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"
#
# [colors.search.matches]
# foreground = "#24273A"
# background = "#A5ADCB"
#
# [colors.footer_bar]
# foreground = "#24273A"
# background = "#A5ADCB"
#

