# Catppuccin macchiato theme for alacritty

[font]
size = 10.5

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 1

[window.padding]
x = 15
y = 15


[colors.normal]
black = "#1e2030"
red = "#a6da95"
green = "#8bd5ca"
yellow = "#91d7e3"
blue = "#8aadf4"
magenta = "#c6a0f6"
cyan = "#7dc4e4"
white = "#eed49f"

[colors.primary]
background = "#1e1e2e"
foreground = "#8aadf4"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.search.matches]
foreground = "#24273A"
background = "#A5ADCB"

[colors.footer_bar]
foreground = "#24273A"
background = "#A5ADCB"

